### PR TITLE
feat: basic fixed strategy support [2.0]

### PR DESCRIPTION
**Pull request by Joelkang**
For my use case I use the `fixed` strategy since I mount the poppers inside of a portal (to prevent z-index) issues. 

I initially went down this path, but it's beginning to seem that the strategy might need to flow down into `getElementClientRect` instead, which seems like a much bigger feat change

### CODE REVIEW

**Comment by FezVrasta** [comment]
Thanks so much for the PR!

Is it really that easy? 🧐

May you try to switch to the `fixed` strategy in the other visual tests and see if they still behave properly?

**Comment by atomiks** [comment]
It's not working with the scrolling container tests

**Comment by atomiks** [comment]
Our current `getElementClientRect` behavior works for `fixed` for all scrolling tests except for `offset-parent.html`. 

I managed to solve it like this for `fixed`:

- Don't take subtract `directOffsetParent` rect
- Include the first `offsetParent` in the `ancestorOffsetParents` array

```js
export default (
  element: Element | VirtualElement,
  // pass in the strategy
  isFixed: boolean = false
): Rect => {
  // ...
  // I think we only need one window stored here to check
  const win = getWindow(unwrappedElement);

  const directOffsetParentRect =
    directOffsetParent instanceof win.Element && !isFixed
      ? getBoundingClientRect(directOffsetParent)
      : { left: 0, top: 0 };

  const ancestorOffsetParents = isFixed ? [directOffsetParent] : [];
  let currentOffsetParent = directOffsetParent;

  while (currentOffsetParent instanceof win.Element) {
    currentOffsetParent = getOffsetParent(currentOffsetParent);
    ancestorOffsetParents.push(currentOffsetParent);
  }

  // ...
};

```

**Comment by atomiks** [comment]
Should `fixed` be the default positioning strategy? What are the differences besides the popper not being affected by clipping parents (which seems like a good thing)? That behavior may be wanted in some cases where the user can choose `absolute`.

**Comment by FezVrasta** [comment]
absolute is generally more preformant, in the simplest cases it doesn’t need to reposition the popper on each scroll.

We could automatically change strategy based on the detected environment though.

**Comment by Joelkang** [comment]
Actually the more I think about it, the more it's unclear to me what `getElementClientRect does--getBoundingClientRect already gets the position relative to the viewport, taking into account scroll, while for offsets relative to the parent, there's `offsetLeft` and `offsetTop`. What does the summing of the ancestral scroll do?

**Comment by atomiks** [comment]
`offsetTop` and `offsetLeft` don't work when the element has transforms or for SVG elements

**Comment by FezVrasta** [comment]
`getBoundingClientRect` returns the offsets relative to the viewport, not to the whole document.

**Comment by FezVrasta** [comment]
I'm going to close this since I just merged #868 that does the same thing, thank you again for the help with the initial implementation!!

**Comment by Joelkang** [comment]
thanks so much @FezVrasta  and @atomiks !

**Pull request closed without merging**
