### PR TITLE
fix: fixed strategy

### PR DESCRIPTION
**Pull request by atomiks**
Continues #868

I renamed the function to `getRectRelativeToOffsetParent`

### CODE REVIEW

**Comment by atomiks** [comment]
These flaky Firefox tests tho... 😒 

It's working in Firefox for me when I manually test it

**Comment by FezVrasta** [comment]
You can manually restart the Firefox tests from the Travis UI 😅 I need to fix them...

**Comment by atomiks** [comment]
I wonder how many images have been spammed to that hosting service due to Firefox lol

**Comment by FezVrasta** [comment]
I hope they don't mind 👀

**Pull request merged**
