### PR TITLE
fix: getBoundingClientRect normalization

### PR DESCRIPTION
**Pull request by atomiks**
Thanks @pat-son

### CODE REVIEW

**Comment by pat-son** [comment]
Should we modify the readme to mention the required polyfills for IE11 support?

**Comment by atomiks** [comment]
https://twitter.com/FezVrasta/status/1206936537709060101

A majority (not many votes admittedly) seem to want to kill it with fire 🔥🤔

**Comment by pat-son** [comment]
If this PR and a couple of voluntary polyfills are all it takes to support IE11, I don't see why not. I have not yet tried the rest of the test cases in IE11.

**Comment by FezVrasta** [comment]
I will add a page to the docs to explain the IE support status.

**Pull request merged**
