### PR TITLE
fix: setOptions should accept a partial

### PR DESCRIPTION
**Pull request by atomiks**

### CODE REVIEW

**Comment by FezVrasta** [comment]
This would make impossible to unset some options though, or remove modifiers

**Comment by atomiks** [comment]
It doesn't?

It lets the previous properties exist without overriding them - you can still override them with this technique.

Before:

```js
// resets `modifiers` and `strategy` back to default (unexpected) 
popper.setOptions({placement: 'right'});
```

With this change, _only_ placement is changed, as expected. If you want to unset things you can re-specify new values for the options. Also the type becomes correct with this change.

**Comment by FezVrasta** [comment]
What about the modifiers? With this change you don't merge the old ones with the new ones.

**Comment by atomiks** [comment]
Aren't shallow updates expected? It works the same as `this.setState()` in React for example

**Comment by FezVrasta** [comment]
If that's the case I would expect `setOptions` to also accept the following signature: `prevOptions => newOptions` so that one can consume the previous options and alter them.

**Comment by atomiks** [comment]
I don't think we need the function signature actually, since the prevOptions exist at `instance.state.options`:

```js
instance.setOptions({
  modifiers: [...instance.state.options.modifiers, newModifier]
});
```

**Comment by atomiks** [comment]
> But, also, if that's the case, then I wouldn't expect the setOptions function to auto merge things, since the useState API of React doesn't do that.

This is different, because it's `options`, not `state`. Every option is optional (obviously), which means you should be able to pass a partial options object, since you can do that with the main constructor.

**Pull request merged**
